# Generated by Django 3.1.1 on 2020-09-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like',
            new_name='likes',
        ),
    ]
