# Generated by Django 3.1.1 on 2020-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
