# Generated by Django 3.1.1 on 2020-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201001_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=2, upload_to='img'),
            preserve_default=False,
        ),
    ]
