# Generated by Django 3.1.1 on 2020-10-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_commints'),
    ]

    operations = [
        migrations.AddField(
            model_name='commints',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
            preserve_default=False,
        ),
    ]
